default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: wonder_cat_factory
  password:

development:
  <<: *default
  database: wonder_cat_factory_development

test:
  <<: *default
  database: wonder_cat_factory_test

production:
  <<: *default
