defaults: &defaults
  users:
    count_per_page: 100
  events:
    count_per_page: 1000
  pictures:
    image:
      rect:
        size:
          width: 600
          height: 600
      thumb:
        size:
          width: 100
          height: 100
  mail:
    sender: noreply@<%= ENV['MAIL_HOST'] %>
  stripe:
    stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
    stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
    stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
    fee_percentage: <%= ENV["FEE_PERCENTAGE"] %>

development:
  <<: *defaults

test:
  <<: *defaults
  mail:
    sender: noreply@mail.wonder-cat-factory.test

production:
  <<: *defaults
