defaults: &defaults
  users:
    count_per_page: 100
  events:
    count_per_page: 1000
  pictures:
    image:
      rect:
        size:
          width: 600
          height: 600
      thumb:
        size:
          width: 100
          height: 100
  mail:
    sender: noreply@<%= ENV['MAIL_HOST'] %>


development:
  <<: *defaults

test:
  <<: *defaults
  mail:
    sender: noreply@mail.wonder-cat-factory.test

production:
  <<: *defaults
