defaults: &defaults
  users:
    count_per_page: 100
  events:
    count_per_page: 10
  pictures:
    image:
      rect:
        size:
          width: 600
          height: 600
      thumb:
        size:
          width: 100
          height: 100

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
